name: TwoG
options:
  bundleIdPrefix: us.defroster
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  TwoG:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - StingrayWarning
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: us.defroster.twog
        PRODUCT_NAME: 2G
        PRODUCT_MODULE_NAME: TwoG
        DISPLAY_NAME: 2G
        INFOPLIST_FILE: StingrayWarning/Resources/Info.plist
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: KA5A6NN3PD
        ENABLE_TESTABILITY: YES
        LSApplicationCategoryType: public.app-category.utilities
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks"]
      configs:
        Release:
          ENABLE_TESTABILITY: YES
    frameworks:
      - CoreTelephony
      - UserNotifications
      - BackgroundTasks
    info:
      path: StingrayWarning/Resources/Info.plist
      properties:
        UIBackgroundModes:
          - processing
          - fetch
        BGTaskSchedulerPermittedIdentifiers:
          - us.defroster.twog.security-monitoring
          - us.defroster.twog.background-refresh
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        TermsOfServiceURL: "https://2g.defroster.us/terms"
        SupportURL: "https://2g.defroster.us"
        PrivacyPolicyURL: "https://2g.defroster.us/privacy"
        ContactURL: "https://2g.defroster.us/contact"
        NSHumanReadableCopyright: "© 2024 2G. All rights reserved."

  TwoGTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - StingrayWarningTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: us.defroster.twogTests
      PRODUCT_NAME: 2GTests
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: KA5A6NN3PD
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/2G.app/2G
      BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: TwoG

  TwoGUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - StingrayWarningUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: us.defroster.twogUITests
      PRODUCT_NAME: 2GUITests
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: KA5A6NN3PD
      GENERATE_INFOPLIST_FILE: YES
      TEST_TARGET_NAME: TwoG
    dependencies:
      - target: TwoG

schemes:
  TwoG:
    build:
      targets:
        TwoG: all
        TwoGTests:
          - run
          - test
          - profile
          - analyze
        TwoGUITests:
          - run
          - test
          - profile
          - analyze
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - TwoGTests
        - TwoGUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      build:
        targets:
          TwoG: all
