name: StingrayWarning
options:
  bundleIdPrefix: us.defroster
  deploymentTarget:
    iOS: "16.0"
  developmentLanguage: en
  xcodeVersion: "15.0"

targets:
  StingrayWarning:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - StingrayWarning
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: us.defroster.stingraywarning
      PRODUCT_NAME: Stingray Warning
      DISPLAY_NAME: Stingray Warning
      INFOPLIST_FILE: StingrayWarning/Resources/Info.plist
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: KA5A6NN3PD
      ENABLE_TESTABILITY: YES
      LSApplicationCategoryType: public.app-category.utilities
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      TARGETED_DEVICE_FAMILY: "1,2"
      LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks"]
    frameworks:
      - CoreTelephony
      - UserNotifications
      - CoreLocation
      - BackgroundTasks
    info:
      path: StingrayWarning/Resources/Info.plist
      properties:
        UIBackgroundModes:
          - processing
          - fetch
        BGTaskSchedulerPermittedIdentifiers:
          - us.defroster.stingraywarning.security-monitoring
          - us.defroster.stingraywarning.background-refresh
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        NSUserTrackingUsageDescription: "This app monitors cellular network security to detect potential IMSI catchers and other threats."
        NSLocationWhenInUseUsageDescription: "Location is used to provide context for network security alerts and help identify suspicious patterns."
        NSLocationAlwaysAndWhenInUseUsageDescription: "Location is used to provide context for network security alerts and help identify suspicious patterns."
        TermsOfServiceURL: "https://stingraywarning.defroster.us/terms"
        SupportURL: "https://stingraywarning.defroster.us"
        PrivacyPolicyURL: "https://stingraywarning.defroster.us/privacy"
        ContactURL: "https://stingraywarning.defroster.us/contact"
        NSHumanReadableCopyright: "© 2024 Stingray Warning. All rights reserved."

  StingrayWarningTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - StingrayWarningTests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: us.defroster.stingraywarningTests
      PRODUCT_NAME: Stingray WarningTests
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: KA5A6NN3PD
      GENERATE_INFOPLIST_FILE: YES
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Stingray Warning.app/Stingray Warning
      BUNDLE_LOADER: $(TEST_HOST)
    dependencies:
      - target: StingrayWarning

  StingrayWarningUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - StingrayWarningUITests
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: us.defroster.stingraywarningUITests
      PRODUCT_NAME: Stingray WarningUITests
      SWIFT_VERSION: "5.0"
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: KA5A6NN3PD
      GENERATE_INFOPLIST_FILE: YES
      TEST_TARGET_NAME: StingrayWarning
    dependencies:
      - target: StingrayWarning

schemes:
  StingrayWarning:
    build:
      targets:
        StingrayWarning: all
        StingrayWarningTests: all
        StingrayWarningUITests: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - StingrayWarningTests
        - StingrayWarningUITests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      build:
        targets:
          StingrayWarning: all
